### ISSUE TITLE
Speedcurve features

### ISSUE THREAD

**Issue by staabm** [micmro/PerfCascade#193]
Speedcurve describes some nice features on https://speedcurve.com/blog/speedcurve-waterfall/

I leave this link here for inspiration and discussion

**Comment by soulgalore** [comment]
Hey @staabm !
Thanks for the link, you mean showing the screenshot and the color of the bars?

## Screenshots
I think it would be a great idea for PerfCascade to report where the mouse is in the chart. I guess we would should add a line to show exactly where the mouse is pointing and then have a listener that gets the X axis? Practically perf cascade will not show any screensshot because there's no in the HAR format but as you user you can build that on top of perfcascade. For us sitespeed.io it would add up perfectly for https://github.com/sitespeedio/sitespeed.io/issues/1555. And it would work the same for other tools that uses PerfCascade.

## Color bars
Right now the bar shows the timing and the color of the bar, it's been brought up before in #4.  I think it is doable right now if you add your own CSS on top of PerfCascade.

Best
Peter

P.S I think it was actually WebPageTest.org that did this first not SpeedCurve. WebPageTest has the filmstrip view http://wpt.wmftest.org/video/compare.php?tests=170402_Q9_C3-r:1-c:0 and also coloring by content type. Also different lines in the HAR. Creds to the ones that deserves it :)

**Comment by staabm** [comment]
What I like most in the article is

> You can also choose to have the height of each request reflect the content size.

**Comment by soulgalore** [comment]
ok cool, for me personally that makes the graph unreadable but it could be that it works better for others? I'm not a frequent SpeedCurve user so I don't know. Have you tried that look and feel @staabm ?

**Comment by staabm** [comment]
I havent used it frequently. 

Maybe we can find some other way to express the filesize in the graph as it is a important measure

**Comment by soulgalore** [comment]
yep I see your point. Let us create two new issues, one for size and one screenshot.
