### ISSUE TITLE
Publish module to npm/bower

### ISSUE THREAD

**Issue by hmil** [micmro/PerfCascade#53]
Are you going to publish this package on npm and/or bower?

**Comment by micmro** [comment]
Good idea. I will work on this after I'll ve back from my holidays.

On 7 Sep 2016 9:06 AM, "Hadrien Milano" notifications@github.com wrote:

Are you going to publish this package on npm and/or bower?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/micmro/PerfCascade/issues/53, or mute the thread

**Comment by micmro** [comment]
I released an initial version to https://www.npmjs.com/package/perf-cascade, but will need to test it a bit more.
