### ISSUE TITLE
Legends text is from resource timing waterfall (right?)

### ISSUE THREAD

**Issue by soulgalore** [micmro/PerfCascade#68]
<img width="983" alt="screen shot 2016-12-05 at 7 24 03 am" src="https://cloud.githubusercontent.com/assets/540757/20891963/5f656c10-bada-11e6-9334-8a6e69d71a79.png">

I think the app cache etc coming from the original resource timing waterfall, I'll go through it tonight.

**Comment by micmro** [comment]
Right it was from the resource timing. Updated it without thinking :) - thanks for the fit.

I just added " (TLS)" behind "SSL" to clarify, since it usually is TLS nowadays.

Found one small bug - will update CSS before releasing it:
<img width="548" alt="screen shot 2016-12-06 at 8 56 55 pm" src="https://cloud.githubusercontent.com/assets/1680390/20924786/b374b03c-bbf6-11e6-8ceb-0b8d849e8c42.png">

**Comment by micmro** [comment]
I have added a ` ms` unit timing as well.

Did you remove the time range `2054 ms (1421 ms - 3475 ms)` on purpose or was it just based on the data? I'm thinking if I should add it back.

**Comment by soulgalore** [comment]
ohh sorry I think I didn't think about it. Not 100% sure that is valuable, thinking that the values for each most value + total (that I see that I removed too)? But if you like, lets add it :)

**Comment by micmro** [comment]
Will think about it. Have created a new issue (#73) to fix some other timing related thing.

released the current changes via `v0.2.10`
