### ISSUE TITLE
Support Fiddler's SAZ Format?

### ISSUE THREAD

**Issue by ericlaw1979** [micmro/PerfCascade#92]
The HAR viewer is awesome!

Would it be possible to extend this with support for Fiddler's SAZ format? There are millions of Fiddler users out there, and SAZ files are pretty common in a number of communities. The SAZ file format is simple (it's just a ZIP file of traffic and metadata, see http://fiddler.wikidot.com/saz-files). I know there are a number of clientside JavaScript libraries that can decompress ZIPs, so it's only a matter of pulling in one of those and writing some script to parse the timers and other metadata from the XML file for each request/response pair.

**Comment by micmro** [comment]
Hi @ericlaw1979, that's an interesting idea PerfCascade was planned to support multiple formats initially (and we already have a unzip module for `*.zhar` files) but I haven't spend a lot of attention to it anymore since all our work was HAR specific. I will have to think about it a bit and will be on vacation for a few days but once I'm back I will compare the HAR and SAZ format and see if SAZ can fit into our data format.

**Comment by tobli** [comment]
One step to enable this would be to remove the har-entry reference from WaterfallEntry, and pull out all relevant information at parse time (see https://github.com/micmro/PerfCascade/search?utf8=✓&q=rawResource)

**Comment by micmro** [comment]
Hi @ericlaw1979, we've cleaned up the parsing and rendering enough to start looking into this soon. Could you provide us a SAZ files for development testing?
